- hosts: all
  become: false
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          - vim
          - stow
          - zsh
          - git
          - curl
          - unzip
        state: present

    - name: Change user shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ the_user }}"
        shell: /bin/zsh

    - name: Clone dotfiles repo
      ansible.builtin.git:
        repo: https://github.com/ianpogi5/dotfiles.git
        dest: ~/dotfiles

    - name: Run stow
      ansible.builtin.shell: stow --adopt .
      args:
        chdir: ~/dotfiles

    - name: Clone fzf repo
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf
        depth: 1

    - name: Install fzf
      ansible.builtin.shell: ~/.fzf/install --all

    - name: Install zoxide
      ansible.builtin.shell: |
        curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh

    - name: ensure fonts directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory

    - name: Hack exists
      shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Hack*Nerd*Font*"
      register: hack_exists
      ignore_errors: yes

    - name: Download Hack
      when: hack_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Hack.zip
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: yes


