- hosts: "{{ host | default('home') }}"
  become: false
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Install packages
      become: "{{ ansible_become | default(true) }}"
      ansible.builtin.package:
        name:
          - vim
          - stow
          - zsh
          - git
          - curl
          - unzip
          - tar
          - btop
        state: present

    - name: Change user shell to zsh
      become: "{{ ansible_become | default(true) }}"
      ansible.builtin.user:
        name: "{{ the_user }}"
        shell: /bin/zsh

    - name: Clone dotfiles repo
      ansible.builtin.git:
        repo: https://github.com/ianpogi5/dotfiles.git
        dest: ~/dotfiles
        update: true

    - name: Run stow
      ansible.builtin.shell: stow --adopt .
      args:
        chdir: ~/dotfiles

    - name: Clone fzf repo
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf
        update: true
        depth: 1

    - name: Install fzf
      ansible.builtin.shell: ~/.fzf/install --all

    - name: Install zoxide
      ansible.builtin.shell: |
        curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh

    - name: Check if oh my posh exists
      ansible.builtin.stat:
        path: "~/.local/bin/oh-my-posh"
      register: omp

    - name: Install oh my posh
      ansible.builtin.shell: |
        curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/.local/bin
      when: not omp.stat.exists

    - name: Upgrade oh my posh
      ansible.builtin.shell: |
        ~/.local/bin/oh-my-posh upgrade
      when: omp.stat.exists

    - name: Install OMP font
      ansible.builtin.shell: |
        ~/.local/bin/oh-my-posh font install meslo
      when: not omp.stat.exists

    - name: Check if eza exists
      ansible.builtin.stat:
        path: "/usr/bin/eza"
      register: eza

    - name: Install eza
      become: "{{ ansible_become | default(true) }}"
      ansible.builtin.shell: |
        curl -sSfL https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-gnu.tar.gz -o eza.tar.gz
        tar xzf eza.tar.gz
        rm -f eza.tar.gz
        chmod +x eza
        chown root:root eza
        mv eza /usr/bin/eza
      when: not eza.stat.exists

    - name: Clone eza repo
      ansible.builtin.git:
        repo: https://github.com/eza-community/eza-themes.git
        dest: ~/.local/eza-themes
        update: true

    - name: Install eza theme
      ansible.builtin.shell: |
        mkdir -p ~/.config/eza
        ln -sf ~/.local/eza-themes/themes/default.yml ~/.config/eza/theme.yml
      when: not eza.stat.exists
