- hosts: "{{ host | default('home') }}"
  become: false
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Install packages
      become: "{{ ansible_become | default(false) }}"
      ansible.builtin.package:
        name:
          - vim
          - stow
          - zsh
          - git
          - curl
          - unzip
          - tar
        state: present

    - name: Change user shell to zsh
      become: "{{ ansible_become | default(false) }}"
      ansible.builtin.user:
        name: "{{ the_user }}"
        shell: /bin/zsh

    - name: Clone dotfiles repo
      ansible.builtin.git:
        repo: https://github.com/ianpogi5/dotfiles.git
        dest: ~/dotfiles

    - name: Run stow
      ansible.builtin.shell: stow --adopt .
      args:
        chdir: ~/dotfiles

    - name: Clone fzf repo
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf
        depth: 1

    - name: Install fzf
      ansible.builtin.shell: ~/.fzf/install --all

    - name: Install zoxide
      ansible.builtin.shell: |
        curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh

    - name: Install oh my posh
      ansible.builtin.shell: |
        curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/.local/bin

    - name: Install OMP font
      ansible.builtin.shell: |
        ~/.local/bin/oh-my-posh font install meslo

    - name: Install eza
      become: "{{ ansible_become | default(false) }}"
      ansible.builtin.shell: |
        curl -sSfL https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-gnu.tar.gz -o eza.tar.gz
        tar xzf eza.tar.gz
        rm -f eza.tar.gz
        chmod +x eza
        chown root:root eza
        mv eza /usr/bin/eza

    - name: Install eza theme
      ansible.builtin.shell: |
        git clone https://github.com/eza-community/eza-themes.git ~/.local/eza-themes
        mkdir -p ~/.config/eza
        ln -sf ~/.local/eza-themes/themes/default.yml ~/.config/eza/theme.yml
