- hosts: "{{ host | default('kdc') }}"
  become: false
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Install packages
      become: "{{ ansible_become | default(true) }}"
      ansible.builtin.package:
        name:
          - vim
          - stow
          - zsh
          - git
          - curl
          - unzip
          - tar
          - make
        state: present

    - name: Check if btop exists
      ansible.builtin.stat:
        path: "/usr/bin/btop"
      register: btop

    - name: Install btop
      become: "{{ ansible_become | default(true) }}"
      ansible.builtin.package:
        name:
          - btop
        state: present
      when: not btop.stat.exists
      ignore_errors: true
      register: btop_pkg

    - name: Install btop manually
      become: "{{ ansible_become | default(true) }}"
      ansible.builtin.shell: |
        curl -sSfL https://github.com/aristocratos/btop/releases/download/v1.4.0/btop-x86_64-linux-musl.tbz -o btop.tbz
        tar -xvjf btop.tbz
        cd btop
        PREFIX=/usr make install
        cd ..
        rm -fR btop*
      when:
        - btop_pkg is defined
        - (btop_pkg.skipped is defined and not btop_pkg.skipped) or (btop_pkg.failed is defined and btop_pkg.failed)

    - name: Change user shell to zsh
      become: "{{ ansible_become | default(true) }}"
      ansible.builtin.user:
        name: "{{ the_user }}"
        shell: /bin/zsh

    - name: Clone dotfiles repo
      ansible.builtin.git:
        repo: https://github.com/ianpogi5/dotfiles.git
        dest: ~/dotfiles
        update: true

    - name: Run stow
      ansible.builtin.shell: stow --adopt .
      args:
        chdir: ~/dotfiles

    - name: Clone fzf repo
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf
        update: true
        depth: 1

    - name: Check if fzf exists
      ansible.builtin.stat:
        path: "~/.fzf.zsh"
      register: fzf

    - name: Install fzf
      ansible.builtin.shell: ~/.fzf/install --all
      when: not fzf.stat.exists

    - name: Check if zoxide exists
      ansible.builtin.stat:
        path: "~/.local/bin/zoxide"
      register: zoxide

    - name: Install zoxide
      ansible.builtin.shell: |
        curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
      when: not zoxide.stat.exists

    - name: Check if oh my posh exists
      ansible.builtin.stat:
        path: "~/.local/bin/oh-my-posh"
      register: omp

    - name: Install oh my posh
      ansible.builtin.shell: |
        curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/.local/bin
      when: not omp.stat.exists

    - name: Upgrade oh my posh
      ansible.builtin.shell: |
        ~/.local/bin/oh-my-posh upgrade
      when: omp.stat.exists

    - name: Install OMP font
      ansible.builtin.shell: |
        ~/.local/bin/oh-my-posh font install meslo
      when: 
        - not omp.stat.exists
        - font_install is defined and font_install

    - name: Install vim plugins and themes
      ansible.builtin.shell: |
        vim +PlugInstall +qa

    - name: Check if eza exists
      ansible.builtin.stat:
        path: "/usr/bin/eza"
      register: eza

    - name: Install eza
      become: "{{ ansible_become | default(true) }}"
      ansible.builtin.shell: |
        curl -sSfL https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-gnu.tar.gz -o eza.tar.gz
        tar xzf eza.tar.gz
        rm -f eza.tar.gz
        chmod +x eza
        chown root:root eza
        mv eza /usr/bin/eza
      when: not eza.stat.exists

    - name: Clone eza repo
      ansible.builtin.git:
        repo: https://github.com/eza-community/eza-themes.git
        dest: ~/.local/eza-themes
        update: true

    - name: Install eza theme
      ansible.builtin.shell: |
        mkdir -p ~/.config/eza
        ln -sf ~/.local/eza-themes/themes/catppuccin.yml ~/.config/eza/theme.yml

    - name: Check if macchina exists
      ansible.builtin.stat:
        path: "~/.local/bin/macchina"
      register: macchina

    - name: Install macchina
      ansible.builtin.shell: |
        curl -sSfL  https://github.com/Macchina-CLI/macchina/releases/download/v6.4.0/macchina-v6.4.0-linux-gnu-x86_64.tar.gz -o macchina.tar.gz
        tar xzf macchina.tar.gz
        rm -f macchina.tar.gz
        chmod +x macchina
        mv macchina ~/.local/bin/macchina
      when: not macchina.stat.exists

    - name: Clone zsh syntax highlighting repo
      ansible.builtin.git:
        repo: https://github.com/catppuccin/zsh-syntax-highlighting.git
        dest: ~/.local/catppuccin-zsh-syntax-highlighting
        update: true
