
[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "MesloLGM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGM Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGM Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "MesloLGM Nerd Font"
style = "Regular"

[window]
dimensions = { columns = 100, lines = 30 }
opacity = 0.95
blur = true
decorations = "Buttonless"

[bell]
animation = "EaseOut"

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
